// <auto-generated />
using System;
using Avanade.Academia.PcD.Infra.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Avanade.Academia.PcD.Infra.Database.Migrations
{
    [DbContext(typeof(ProjetoContext))]
    [Migration("20220617200214_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Avanade.Academia.PcD.Domain.Entities.BaseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataAtualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("Datetime")
                        .HasColumnName("DataCriacao");

                    b.HasKey("Id");

                    b.ToTable("BaseEntity");
                });

            modelBuilder.Entity("Avanade.Academia.PcD.Domain.Entities.Professor", b =>
                {
                    b.HasBaseType("Avanade.Academia.PcD.Domain.Entities.BaseEntity");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NomeProfessor");

                    b.Property<decimal>("Salario")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("SalarioProfessor");

                    b.ToTable("TblProfessor", (string)null);
                });

            modelBuilder.Entity("Avanade.Academia.PcD.Domain.Entities.Professor", b =>
                {
                    b.HasOne("Avanade.Academia.PcD.Domain.Entities.BaseEntity", null)
                        .WithOne()
                        .HasForeignKey("Avanade.Academia.PcD.Domain.Entities.Professor", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
